[fronts]
web01 ansible_host=192.168.200.11
web02 ansible_host=192.168.200.12

[fronts:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3

[proxy]
proxy01 ansible_host=192.168.200.10

[proxy:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
