name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pull:
    runs-on: self-hosted
    steps:
      - name: Git pull
        run: |
          cd /home/florent/Documents/TP-AIS/Projet-Fil-Rouge
          echo "Déployé le $(date) — commit ${{ github.sha }} par ${{ github.actor }}"
          git fetch origin
          git reset --hard origin/main
